function lambdafig(X1, Y1, M)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Nov-2010 18:21:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,...
    'MarkerEdgeColor',[0.494117647058824 0.184313725490196 0.556862745098039],...
    'MarkerSize',8,...
    'Marker','o',...
    'LineWidth',3,...
    'Color',[0.494117647058824 0.184313725490196 0.556862745098039]);

% Create ylabel
ylabel('$\lambda$','FontName','Times','Interpreter','latex');

% Create xlabel
xlabel('$\mathsf{M}$','FontName','Times','Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times','FontSize',14);
