MODULE VARIAVEIS
  INTEGER :: NSTAGE,NPRIORR,NPRINT,NDTYPE,ACCEPT
  INTEGER :: NR,NRTOTAL,NSIMUL,NS,NCONDMAX,NCHAIN
  INTEGER :: SGN,CONTADORC,CONTADORF,CONTREJ,CONT
  INTEGER :: NNORMA,NCUT
  INTEGER :: DIMR,NINICIO,NSTART
  INTEGER :: NCR,NPCHAIN,NDELTA,NFREQAM
  REAL    :: SIGDE
  REAL    :: CR_DREAM
  REAL    :: TERRORCC,TERRORNC,TERRORCF,TERRORNF
  REAL    :: TLRATIOF,TLRATIOC,TPRATIO
  INTEGER :: NLBDPOSI
  REAL    :: YNEW,YOLD,JUMP
  INTEGER :: TIPOVAR, ERROSIMULADOR
  LOGICAL :: SINALDREAM
  CHARACTER(LEN=128) :: FILEIN,NAME_OUT,FILEINI
  CHARACTER(LEN=128) :: FILERROR
  CHARACTER(LEN=128) ,ALLOCATABLE,DIMENSION(:,:):: FILE_OUTEXP
  CHARACTER(LEN=128) ,DIMENSION(1:10):: FILE_OUT,FILE_EXT,FILE_VAL
  CHARACTER(LEN=128) ,DIMENSION(1:10):: FILE_VET,FILE_THE
  CHARACTER(LEN=128) ,DIMENSION(1:10):: FILE_MM,FILE_MU,FILE_K
  CHARACTER(LEN=128) ,DIMENSION(1:10):: FILE_INFIELD,FILEREF
  CHARACTER(LEN=128) ,DIMENSION(1:10):: FILEAM,NAMEPRIOR
  CHARACTER(LEN=128) ,DIMENSION(1:10,1:40):: NAME_AVET
  INTEGER,ALLOCATABLE,DIMENSION(:,:)   :: NID,NIDALL
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: VARPROP,NFREQ
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: VETCONT
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: GERATIPO,LIKETIPO,NLPRIOR
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: NWELLS,NDADOS,NDADOSI,NSEED,NUPSC
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: NCOND,NX,NY,NZ,NFLAG,MKL,NTOTAL
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: NPROPOSAL,NUM_AVET,NUM_AVETOLD
  INTEGER,ALLOCATABLE,DIMENSION(:)     :: NLBD,NLBDVET,NZMIN,NKIND
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: LOGERRORCF,ERRORCC
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: ERRORNC,ERRORCF,ERRORNF
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: SIGMA2C,SIGMA2F
  REAL   ,ALLOCATABLE,DIMENSION(:,:,:) :: VET
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: ALPHA,DIMX
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: DIMY,DIMZ,SIG,VARIAN,FBETA
  REAL   ,ALLOCATABLE,DIMENSION(:,:,:) :: REFDATA,REFAMOS
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: ERRORF
  REAL   ,ALLOCATABLE,DIMENSION(:,:)   :: LOGPERM,LOGPERMN
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: PRATIO,LRATIOF,LRATIOC
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: MAXDATA,NORMA_L2_REF
  REAL   ,ALLOCATABLE,DIMENSION(:,:)   :: THETA,THETAN
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: NEWLBD,OLDLBD,LBDFIXO
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: YNEWLBD,YOLDLBD
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: XLBDMEAN,XLBDSD,XLBDBETA
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: XLBDS,CLBDS,ZMAX
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: XRMVN_MEAN,XRMVN
  REAL   ,ALLOCATABLE,DIMENSION(:,:)   :: XRMVN_VET,MATDE
  REAL   ,ALLOCATABLE,DIMENSION(:)     :: COVMATUP,COVMATDOWN,COVMATID
  REAL   ,ALLOCATABLE,DIMENSION(:,:)   :: JVET,JVETALL,PCRALL
END MODULE VARIAVEIS
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
