function maxerrorfig(XData1, YData1, XData2, YData2)
%CREATEFIGURE(XDATA1,YDATA1,XDATA2,YDATA2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 01-Aug-2011 15:36:43

% Create figure
figure1 = figure('XVisual',...
    '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YColor',[0 0 0],'XColor',[0 0 0],...
    'FontSize',18,'YGrid','on','XGrid','on',...
    'FontName','Times New Roman');
box(axes1,'on');

% Create line
line(XData1,YData1,'Parent',axes1,'LineWidth',2,'Color',[0 0 0]);

% Create xlabel
xlabel('Time','FontSize',16,'Color',[0 0 0]);
xlim(axes1,[0 .2])
% Create ylabel
ylabel('$\mbox{m\ \ a x}{|M_{\ \ source}|}$','FontSize',16,'Color',[0 0 0],'Interpreter','latex');

% Create axes
% axes2 = axes('Parent',figure1,'YAxisLocation','right','XAxisLocation','top',...
%     'FontSize',12,'YColor',[0 0 1],'XColor',[0 0 1],...
%     'FontSize',18,'FontName','Times New Roman',...
%     'Color','none');
% 
% % Create line
% line(XData2,YData2,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
% 
% % Create xlabel
% xlabel('Time','FontSize',16,'VerticalAlignment','bottom');
% 
% % Create ylabel
% ylabel('M_{source} (TWO-WAY)','FontSize',16,'VerticalAlignment','cap');

