function fig(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
xmax = max(max(X1),max(X2));
ymax = max(max(Y1),max(Y2));
xmin = min(min(X1),min(X2));
ymin = min(min(Y1),min(Y2));
%  Auto-generated by MATLAB on 20-Sep-2017 10:35:47

% Create figure
figure1 = figure('XVisual',...
    '0xce (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','LineWidth',4,...
    'FontSize',20,'FontName','Times New Roman','FontAngle','italic');
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',3,'DisplayName','Sol. analítica','Color',[0 0 0]);

% Create plot
plot(X2,Y2,'MarkerSize',6,'Marker','o','LineStyle','none',...
    'DisplayName','Aprox. numérica','Color',[0 0 1]);

xlim([xmin xmax]);
ylim([ymin*0.8 ymax*1.1]);

% Create xlabel
xlabel('x','FontSize',28,'FontName','Times New Roman','FontAngle','italic');

% Create ylabel
ylabel('s','FontSize',28,'FontName','Times New Roman','FontAngle','italic');

