function figc(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
xmax = max(max(X1),max(X2));
ymax = max(max(Y1),max(Y2))*1.1;
xmin = min(min(X1),min(X2));
ymin = min(min(Y1),min(Y2))*0.8;
dx   = (xmax-xmin);
dy   = ymax-ymin;
%  Auto-generated by MATLAB on 20-Sep-2017 11:58:37

% Create figure
figure1 = figure('XVisual',...
    '0xce (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'Color',[0.07843 0.1686 0.549]);

% Create axes
axes1 = axes('Parent',figure1,'ZColor',[1 0.6941 0.3922],'YGrid','on',...
    'YColor',[1 0.6941 0.3922],...
    'XGrid','on',...
    'LineWidth',3,...
    'DataAspectRatio',[1 2*(dy/dx) 1],...
    'XColor',[1 0.6941 0.3922],...
    'FontSize',28,...
    'FontName','Times New Roman',...
    'FontAngle','italic',...
    'Color',[0.07843 0.1686 0.549]);

% Uncomment the following line to preserve the X-limits of the axes
xlim([xmin xmax]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim([ymin ymax]);

box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X2,Y2,'MarkerSize',6,'Marker','o','LineStyle','--','Color',[0.6784 0.9216 1],...
    'DisplayName','Aprox. numérica');
% Create plot
plot(X1,Y1,'LineWidth',3,'Color',[1 1 0],'DisplayName','Sol. analítica');

% Create xlabel
xlabel('x','FontSize',28,'FontName','Times New Roman','FontAngle','italic',...
    'Color',[1 0.6941 0.3922]);

% Create ylabel
ylabel('s','FontSize',28,'FontName','Times New Roman','FontAngle','italic',...
    'Color',[1 0.6941 0.3922]);

