function sat_figure_corte(xdata1,zdata1,cc,dd,A,B)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 16-Feb-2011 12:02:36

% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[18.92 14.57],...
    'PaperOrientation','landscape',...
    'PaperUnits','centimeters');
if(abs(A-B)<1e-5)
    posi=[0.1 0.11 0.775 0.815];
else
    posi=[0.1 0.11 0.775 0.815];
end
% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 dd*0.2 dd*0.4 dd*0.6 dd*0.8 dd*1],...
    'YMinorTick','on',...
    'YGrid','on',...
    'XTick',[0 A*0.2 A*0.4 A*0.6 A*0.8 A*1],...
    'XMinorTick','on',...
    'XGrid','on',...
    'FontSize',16,...
    'FontName','times',...
    'DataAspectRatio',[1 1.5*abs(dd-cc)/A 1],...
    'CLim',[cc dd],...
    'Position',posi);
% Create axes
xlim(axes1,[0 A]);
ylim(axes1,[cc dd*1.1]);
grid(axes1,'on');
hold(axes1,'all');
box on

% Create surf
plot(xdata1,zdata1,...
    'MarkerEdgeColor',[0 0 0],'Marker','o','LineWidth',1,'Color',[0 0 1]);
    hold off
% Create zlabel
ylabel('s_{w}','Visible','on','FontSize',20,'FontName','times','Interpreter','tex');
xlabel('x','Visible','on','FontSize',20,'FontName','times','Interpreter','tex');
view(0,90.0)

