function sat_figureOCTAVE(xdata1,ydata1,zdata1,A,B,aa,bb,cc,dd,C,D,t,clim1,clim2)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 16-Feb-2011 12:02:36

% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[18.92 10.57],...
    'PaperOrientation','landscape',...
    'PaperUnits','centimeters');

box on
% Create surf
    surf(xdata1,ydata1,zdata1);
    shading('interp');
%    shading('flat');
%    shading('faceted');
%    alpha(0.5); 
    hold on
%    contour(xdata1,ydata1,zdata1,8,...
%    'LineWidth',1.0);%,'ShowText','on'); 
    hold off
% Create zlabel
zlabel('S_w','Visible','off','FontSize',20,'FontName','times');
xlabel('x','Visible','off','FontSize',20,'FontName','times');
ylabel('y','Visible','off','FontSize',20,'FontName','times');
view(0,90.0)
% Create colorbar
%if(abs(A-B)<1e-5)
%    colorbar('peer',axes1,[0.8522 0.1071 0.04216 0.8071],'FontSize',15,'FontName','times');
%else
%    if(abs(A/B)<2.1)
%        colorbar('peer',axes1,[0.9 0.377 0.04216 0.52],'FontSize',15,'FontName','times');
%    else
%        colorbar('peer',axes1,[0.9 0.632 0.04216 0.26],'FontSize',15,'FontName','times');
%    end
%end
%
% % Create textbox
% tempo = num2str(t,'%1.3f');
% if(abs(A-B)<1e-5)
%     annotation(figure1,'textbox',[0.4331 0.9238 0.1151 0.03881],...
%         'String',{['t =' tempo]},...
%         'HorizontalAlignment','center',...
%         'FitBoxToText','off',...
%         'LineStyle','none','FontName','times','FontSize',12);
% else
%     if(abs(A-B)<2.1)
%         annotation(figure1,'textbox',[0.45 0.92 0.1151 0.03881],...
%             'String',{['t =' tempo]},...
%             'HorizontalAlignment','center',...
%             'FitBoxToText','off',...
%             'LineStyle','none','FontName','times','FontSize',12);
%     else
%         annotation(figure1,'textbox',[0.45 0.92 0.1151 0.03881],...
%             'String',{['t =' tempo]},...
%             'HorizontalAlignment','center',...
%             'FitBoxToText','off',...
%             'LineStyle','none','FontName','times','FontSize',12);
%     end        
% end
axis("square")



