function bbfigure2(Er)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-Jul-2018 09:23:08
% A = min(min(min(X1)));
% A = min(min(min(min(X2))),A);
% A = min(min(min(min(X3))),A);
% B = max(max(max(X1)));
% B = max(max(max(max(X2))),B);
% B = max(max(max(max(X3))),B);
A = min(Er);
B = max(Er);
N = size(Er,2);
% Create figure
figure1 = figure('XVisual',...
    '0xde (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Times New Roman',...
    'DataAspectRatio',[1 2*(B-A)/(N) 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
X1 = [1:N]';
plot(X1,Er,'Marker','none','LineStyle','-','LineWidth',3,'Color',[0 0 0]);
ylim([A B]);

% Create xlabel
xlabel('Accepted','FontSize',18,'FontName','Times New Roman');

% Create ylabel
ylabel('Error','FontSize',18,'FontName','Times New Roman');

