clear;
base_name = 'prod_D3_KL20_0';
%dados=load('../prod/prodF_ref_0.dat');
dados=load('../SIMULADOR_VISCOELASTICO/exp/desl/desl_ref_0.dat');
ref=dados;
%
file_name = ['../twoStage/select_prod/' base_name '.dat']
%
% Create figure
figure1 = figure()
B=-0.8;
A=-1.55;
%B=1e-2;
%A=1e-5;
C=min(dados(:,1));
C=-0
D=max(dados(:,1))*1.01;

dasp=[1 1.*(B-A)/(D-C) 200];
% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Times New Roman',...
    'DataAspectRatio',dasp);
box(axes1,'on');
hold(axes1,'all');


plot(dados(:,1),dados(:,2),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 1')
plot(dados(:,1),dados(:,3),'Parent',axes1,'Color',[0 0 1],...
    'MarkerSize',4,'Marker','s','LineStyle','none','DisplayName','ref. 2')
plot(dados(:,1),dados(:,4),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 3')
plot(dados(:,1),dados(:,5),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',4,'Marker','s','LineStyle','none','DisplayName','ref. 4')
plot(dados(:,1),dados(:,6),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 5')
plot(dados(:,1),dados(:,7),'Parent',axes1,'Color',[0.2 0.2 0.5],...
    'MarkerSize',4,'Marker','s','LineStyle','none','DisplayName','ref. 6')
plot(dados(:,1),dados(:,8),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 7')
plot(dados(:,1),dados(:,9),'Parent',axes1,'Color',[1 0 1],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 8')
plot(dados(:,1),dados(:,10),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 9')
plot(dados(:,1),dados(:,11),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 10')
plot(dados(:,1),dados(:,12),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 11')
plot(dados(:,1),dados(:,13),'Parent',axes1,'Color',[1 1 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 12')
plot(dados(:,1),dados(:,14),'Parent',axes1,'Color',[.8 .8 .8],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 13')
plot(dados(:,1),dados(:,15),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 14')
plot(dados(:,1),dados(:,16),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 15')
% plot(dados(:,1),dados(:,17),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 16')
% plot(dados(:,1),dados(:,18),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 17')
% plot(dados(:,1),dados(:,19),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 18')
% plot(dados(:,1),dados(:,20),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 19')
% plot(dados(:,1),dados(:,21),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 20')
% plot(dados(:,1),dados(:,22),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 21')
% plot(dados(:,1),dados(:,23),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 22')
% plot(dados(:,1),dados(:,24),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 23')
% plot(dados(:,1),dados(:,25),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 24')
% plot(dados(:,1),dados(:,26),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'Marker','o','LineStyle','none','DisplayName','ref. 25')
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dados=load(file_name);
%dados=load('../../MCMC/reject_prod/prod_chn0-20_16000.dat');
%dados=load('../conc/conc_amostra_0.dat');
plot(dados(:,1),dados(:,2),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 1')
plot(dados(:,1),dados(:,3),'Parent',axes1,'Color',[0 0 1],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 2')
plot(dados(:,1),dados(:,4),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 3')
plot(dados(:,1),dados(:,5),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 4')
plot(dados(:,1),dados(:,6),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 5')
plot(dados(:,1),dados(:,7),'Parent',axes1,'Color',[0.2 0.2 .5],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 6')
plot(dados(:,1),dados(:,8),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 7')
plot(dados(:,1),dados(:,9),'Parent',axes1,'Color',[1 0 1],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 8')
plot(dados(:,1),dados(:,10),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 9')
plot(dados(:,1),dados(:,11),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 10')
plot(dados(:,1),dados(:,12),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 11')
plot(dados(:,1),dados(:,13),'Parent',axes1,'Color',[1 1 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 12')
plot(dados(:,1),dados(:,14),'Parent',axes1,'Color',[.8 .8 .8],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 13')
plot(dados(:,1),dados(:,15),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 14')
plot(dados(:,1),dados(:,16),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 15')
% plot(dados(:,1),dados(:,17),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 16')
% plot(dados(:,1),dados(:,18),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 17')
% plot(dados(:,1),dados(:,19),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 18')
% plot(dados(:,1),dados(:,20),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 19')
% plot(dados(:,1),dados(:,21),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 20')
% plot(dados(:,1),dados(:,22),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 21')
% plot(dados(:,1),dados(:,23),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 22')
% plot(dados(:,1),dados(:,24),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 23')
% plot(dados(:,1),dados(:,25),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 24')
% plot(dados(:,1),dados(:,26),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',4,'LineWidth',2,'DisplayName','simul. 25')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
xlim(axes1,[C D])
ylim(axes1,[A B])
% Create xlabel
xlabel('t','FontSize',20,'FontName','Times New Roman','FontAngle','italic');

% Create ylabel
ylabel('p','FontSize',20,'FontName','Times New Roman','FontAngle','italic');
% Create legend
%legend1 = legend(axes1,'show');
set(legend1,'Location','NorthWest','FontSize',10);
set(legend1,'Box','off');

% Print
base=['../figuras/conc_' base_name];
%print('-djpeg90',base)
print('-depsc','-r100',base)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% NORMA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
norma=norm(ref(:,2:end))
norma=norm(ref(:,2:end)-dados(:,2:end))/norma;
fprintf('ERRO RELATIVO = %e\n',norma)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear
