function figCVP(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Nov-2013 16:31:09
B=max(max(YMatrix1));
A=min(min(YMatrix1));
%B=1e-2;
%A=1e-5;
C=min(X1);
D=max(X1)*1.01;
dasp=[1 1.*(B-A)/(D-C) 200];
% Create figure
figure1 = figure('XVisual',...
    '0xcc (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman',...
    'DataAspectRatio',dasp);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Color',[0 0 0]);
set(plot1(1),'Marker','o','LineStyle','none','DisplayName','computed');
set(plot1(2),'LineWidth',2,'DisplayName','theoretical');

% Create xlabel
xlabel('$t$','Interpreter','latex','FontWeight','bold','FontSize',14,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('$\mathcal{C}_k$','Interpreter','latex','FontSize',14,...
    'FontName','Times New Roman');
legend1 = legend(axes1,'show');
set(legend1,'Location','NorthEast','FontSize',10);
set(legend1,'Box','off');
%
vari=B-A;
for i=1:length(YMatrix1)
    if(C>vari*.8)
        i
        break
    end
end
disp(['Tempo para decair ate 20% de valor maximo:'...
    num2str(i*(X1(2)-X1(1)))])




