function figlambdas(X1, Y1, Y2, Y3, flag, maxi,mini)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

if(flag==1)
    %  Auto-generated by MATLAB on 19-Dec-2011 08:09:49
    B=max(Y1)*1.1;
    A=mini;%min(Y1);
    if(maxi>0)
        B=maxi;
    end
    C=min(X1);
    D=max(X1);

    % Create figure
    figure1 = figure('XVisual',...
        '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

    % Create axes
    dasp=[1 (B-A)/(D-C) 200];
    %axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    axes1 = axes('Parent',figure1,'YScale','linear','YMinorTick','on',...
        'FontSize',14,...
        'FontName','Times New Roman',...
        'DataAspectRatio',dasp);
    box(axes1,'on');
    hold(axes1,'all');
    xlim(axes1,[0 D])
    ylim(axes1,[A B])

    % Create semilogy
    % plot(X1,Y1,'Parent',axes1,'MarkerSize',9,'Marker','o','LineWidth',2,...
    %     'DisplayName','Independent sampling',...
    %     'Color',[0 0 0]);
    semilogy(X1,Y1,'Parent',axes1,'MarkerSize',9,'Marker','none','LineWidth',2,...
        'DisplayName','Independent sampling',...
        'Color',[0 0 0]);

    % Create xlabel
    xlabel('Accepted iterations','FontWeight','bold','FontSize',16,...
        'FontName','Times New Roman');

    % Create ylabel
    % ylabel('Fractional flow error','FontWeight','bold','FontSize',16,...
    %     'FontName','Times New Roman');
    ylabel('Total relative error','FontWeight','bold','FontSize',16,...
        'FontName','Times New Roman');

    % Create legend
    % legend(axes1,'show');
else
    %  Auto-generated by MATLAB on 19-Dec-2011 08:09:49
    B=max(max(Y2),max(Y3))*1.1;
    A=mini;%min(Y1);
    if(maxi>0)
        B=maxi;
    end
    C=min(X1);
    D=max(X1);

    % Create figure
    figure1 = figure('XVisual',...
        '0x27 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

    % Create axes
    dasp=[1 (B-A)/(D-C) 200];
    %axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    axes1 = axes('Parent',figure1,'YScale','linear','YMinorTick','on',...
        'FontSize',14,...
        'FontName','Times New Roman',...
        'DataAspectRatio',dasp);
    box(axes1,'on');
    hold(axes1,'all');
    xlim(axes1,[0 D])
    ylim(axes1,[A B])

    % Create semilogy
    % plot(X1,Y1,'Parent',axes1,'MarkerSize',9,'Marker','o','LineWidth',2,...
    %     'DisplayName','Independent sampling',...
    %     'Color',[0 0 0]);
%     semilogy(X1,Y2,'Parent',axes1,'MarkerSize',9,'Marker','none',...
%         'LineWidth',2,'LineStyle','--','DisplayName','p',...
%         'Color',[0 0 0]);
    semilogy(X1,Y3,'Parent',axes1,'MarkerSize',9,'Marker','none',...
        'LineWidth',2,'LineStyle','-','DisplayName','\lambda_t',...
        'Color',[0 0 0]);

    % Create xlabel
    xlabel('Accepted iterations','FontWeight','bold','FontSize',16,...
        'FontName','Times New Roman');

    % Create ylabel
    % ylabel('Fractional flow error','FontWeight','bold','FontSize',16,...
    %     'FontName','Times New Roman');
    ylabel('Correlation length','FontWeight','bold','FontSize',16,...
        'FontName','Times New Roman');

    % Create legend
    legend1=legend(axes1,'show');
    set(legend1,'FontAngle','italic');
    set(legend1,'box','off');
end
    
