function figMEANS(X1, YMatrix1,media)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 28-Oct-2013 10:24:02

% Create figure
figure1 = figure(55);
B=max(max(YMatrix1))*1.1;
A=min(min(YMatrix1));
%B=1.5e+1;
C=min(X1);
D=max(X1);

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','XMinorTick','on',...
    'FontSize',14,...
    'FontName','Times New Roman',...
    'DataAspectRatio',[1 2*(B-A)/(D-C) 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Marker','+','DisplayName','$\phi$','Color',[0 0 0]);
set(plot1(2),'MarkerEdgeColor',[0 0 0],'Marker','o','Color',[0 0 0],...
    'DisplayName','$k$');
hold on
% Create plot
plot([C D],[media media],'Parent',axes1,'LineWidth',3,'Color',[1 0 0],...
    'DisplayName','mean');
xlim(axes1,[C D])
ylim(axes1,[A B])

% Create xlabel
xlabel('$n$','Interpreter','latex','FontSize',20,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('$\langle \theta_\alpha \rangle$','Interpreter','latex',...
    'FontSize',20,...
    'FontName','Times New Roman');

% Create legend
leg1 = legend(axes1,'show');
set(leg1,'Interpreter','latex')

