function figure_error(N,Fref1,Fref2,Fref3,xdata,X1,X2,X3,sxd)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-Jul-2018 09:23:08
% A = min(min(min(X1)));
% A = min(min(min(min(X2))),A);
% A = min(min(min(min(X3))),A);
% B = max(max(max(X1)));
% B = max(max(max(max(X2))),B);
% B = max(max(max(max(X3))),B);
A = min(min(min(Fref2),min(Fref1)),min(Fref3));
B = max(max(max(Fref2),max(Fref1)),max(Fref3));

% Create figure
figure1 = figure('XVisual',...
    '0xde (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Times New Roman',...
    'DataAspectRatio',[1 1*(B-A)/(max(xdata)-min(xdata)) 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
for i=0:1000
    x1=X1(N-i,:,1);
    x2=X2(N-i,:,1);
    x3=X3(N-i,:,1);
    Fsn = [blackbox(xdata,x1) blackbox(xdata,x2)...
        blackbox(xdata,x3)];
    plot(xdata,Fsn(1:sxd),'ro-');
    plot(xdata,Fsn(sxd+1:2*sxd),'bo-');
    plot(xdata,Fsn(2*sxd+1:3*sxd),'ko-');
end
plot(xdata,Fref1,'r-','LineWidth',3);
plot(xdata,Fref2,'b-','LineWidth',3);
plot(xdata,Fref3,'k-','LineWidth',3);

ylim([A B]);

% Create xlabel
xlabel('x','FontSize',18,'FontName','Times New Roman');

% Create ylabel
ylabel('f(x)','FontSize',18,'FontName','Times New Roman');

