clear;
loc=100;
jump=2;
N=200;
Nini=100;
Nfim=430;
Nt=(Nfim-Nini)+1;
base_name = 'pre_MC_';
%base_name = 'pre_MCMC_';
%dados=load('../prod/prodF_ref_0.dat');
dados=load('../simul_comp/exp/pressao/pre_ref_0.dat');
ref=dados;
%
dmedio=zeros(size(ref,1),size(ref,2));
for i=Nini:Nfim
    istr=num2str(i,5);
    file_name = ['../simul_comp/exp/pressao/' base_name istr '.dat']
    data=load(file_name);
    dmedio=dmedio+data;
end
%
% Create figure
figure1 = figure()
B=5.1e8;
A=3.7e8;
%B=1e-2;
%A=1e-5;
C=min(dados(:,1));
D=max(dados(:,1))*1.01;

dasp=[1 1.*(B-A)/(D-C) 200];
% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Times New Roman',...
    'DataAspectRatio',dasp);
box(axes1,'on');
hold(axes1,'all');


plot(dados(1:jump:end,1),dados(1:jump:end,2),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 1')
plot(dados(1:jump:end,1),dados(1:jump:end,3),'Parent',axes1,'Color',[0 0 1],...
    'MarkerSize',6,'Marker','s','LineStyle','none','DisplayName','ref. 2')
plot(dados(1:jump:end,1),dados(1:jump:end,4),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 3')
plot(dados(1:jump:end,1),dados(1:jump:end,5),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',6,'Marker','s','LineStyle','none','DisplayName','ref. 4')
plot(dados(1:jump:end,1),dados(1:jump:end,6),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 5')
plot(dados(1:jump:end,1),dados(1:jump:end,7),'Parent',axes1,'Color',[0.2 0.2 0.5],...
    'MarkerSize',6,'Marker','s','LineStyle','none','DisplayName','ref. 6')
% plot(dados(1:jump:end,1),dados(1:jump:end,8),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 7')
% plot(dados(1:jump:end,1),dados(1:jump:end,9),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 8')
% plot(dados(1:jump:end,1),dados(1:jump:end,10),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 9')
% plot(dados(1:jump:end,1),dados(1:jump:end,11),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 10')
% plot(dados(1:jump:end,1),dados(1:jump:end,12),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 11')
% plot(dados(1:jump:end,1),dados(1:jump:end,13),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 12')
% plot(dados(1:jump:end,1),dados(1:jump:end,14),'Parent',axes1,'Color',[.8 .8 .8],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 13')
% plot(dados(1:jump:end,1),dados(1:jump:end,15),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 14')
% plot(dados(1:jump:end,1),dados(1:jump:end,16),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 15')
% plot(dados(1:jump:end,1),dados(1:jump:end,17),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 16')
% plot(dados(1:jump:end,1),dados(1:jump:end,18),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 17')
% plot(dados(1:jump:end,1),dados(1:jump:end,19),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 18')
% plot(dados(1:jump:end,1),dados(1:jump:end,20),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 19')
% plot(dados(1:jump:end,1),dados(1:jump:end,21),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 20')
% plot(dados(1:jump:end,1),dados(1:jump:end,22),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 21')
% plot(dados(1:jump:end,1),dados(1:jump:end,23),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 22')
% plot(dados(1:jump:end,1),dados(1:jump:end,24),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 23')
% plot(dados(1:jump:end,1),dados(1:jump:end,25),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 24')
% plot(dados(1:jump:end,1),dados(1:jump:end,26),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'Marker','o','LineStyle','none','DisplayName','ref. 25')
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dados=dmedio/Nt;
%dados=load('../../MCMC/reject_prod/prod_chn0-20_16000.dat');
%dados=load('../conc/conc_amostra_0.dat');
plot(dados(:,1),dados(:,2),'Parent',axes1,'Color',[1 0 0],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  1')
plot(dados(:,1),dados(:,3),'Parent',axes1,'Color',[0 0 1],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  2')
plot(dados(:,1),dados(:,4),'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  3')
plot(dados(:,1),dados(:,5),'Parent',axes1,'Color',[0 1 0],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  4')
plot(dados(:,1),dados(:,6),'Parent',axes1,'Color',[0 1 1],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  5')
plot(dados(:,1),dados(:,7),'Parent',axes1,'Color',[0.2 0.2 .5],...
    'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  6')
% plot(dados(:,1),dados(:,8),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  7')
% plot(dados(:,1),dados(:,9),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  8')
% plot(dados(:,1),dados(:,10),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  9')
% plot(dados(:,1),dados(:,11),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  10')
% plot(dados(:,1),dados(:,12),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  11')
% plot(dados(:,1),dados(:,13),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  12')
% plot(dados(:,1),dados(:,14),'Parent',axes1,'Color',[.8 .8 .8],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  13')
% plot(dados(:,1),dados(:,15),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  14')
% plot(dados(:,1),dados(:,16),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  15')
% plot(dados(:,1),dados(:,17),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  16')
% plot(dados(:,1),dados(:,18),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  17')
% plot(dados(:,1),dados(:,19),'Parent',axes1,'Color',[1 0 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  18')
% plot(dados(:,1),dados(:,20),'Parent',axes1,'Color',[0 1 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  19')
% plot(dados(:,1),dados(:,21),'Parent',axes1,'Color',[0 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  20')
% plot(dados(:,1),dados(:,22),'Parent',axes1,'Color',[0 1 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  21')
% plot(dados(:,1),dados(:,23),'Parent',axes1,'Color',[1 1 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  22')
% plot(dados(:,1),dados(:,24),'Parent',axes1,'Color',[1 0 0],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  23')
% plot(dados(:,1),dados(:,25),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  24')
% plot(dados(:,1),dados(:,26),'Parent',axes1,'Color',[0 0 1],...
%     'MarkerSize',6,'LineWidth',2,'DisplayName','mean simul.  25')
plot([loc loc],[A B],'Parent',axes1,'Color',[0 0 0],...
    'MarkerSize',6,'LineWidth',1,'LineStyle','--',...
    'DisplayName','time to select')

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
xlim(axes1,[0 D])
ylim(axes1,[A B])
% Create xlabel
xlabel('t','FontSize',20,'FontName','Times New Roman','FontAngle','italic');

% Create ylabel
ylabel('p','FontSize',20,'FontName','Times New Roman','FontAngle','italic');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','SouthWest','FontSize',10);
set(legend1,'Box','off');

% Print
base=['./../../figuras/pres_' base_name];
%print('-djpeg90',base)
print('-depsc','-r100',base)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% NORMA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
norma=norm(ref(:,2:end))
norma=norm(ref(:,2:end)-dados(:,2:end))/norma;
fprintf('ERRO RELATIVO = %e\n',norma)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear
