function Rfigure(X1, Y1, transp)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Oct-2018 15:46:25
A=min(min(Y1))*0.975;
B=max(max(Y1))*1.025;
aux = max(abs(B-1),abs(A-1));
A = 0.8;%1-aux;
B = 2;%1+aux;
C=min(X1);
D=max(X1);
% Create figure
figure1 = figure();
if(transp==1)
    fig = gcf;
    fig.Color = 'none';
    fig.InvertHardcopy = 'off';
end
% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'YMinorTick','on','XMinorTick','on',...
    'FontSize',16,'FontName','Times','FontWeight','bold',...
    'DataAspectRatio',[((D-C)/(B-A)) 3 1],'Color','none');
box(axes1,'on');
hold(axes1,'all');

% Create plot
for i=1:size(Y1,2)
    plot(X1,Y1(:,i),'LineWidth',3,'Color',[0 0 ((i-1)/size(Y1,2))]);
end
plot(X1,1+0.0*Y1(:,i),'LineWidth',1,'LineStyle','--','Color',[0.5 0.5 0.5]);
plot(X1,1.2+0.0*Y1(:,i),'LineWidth',1,'LineStyle','--','Color',[0.5 0.5 0.5]);

% Create xlabel
xlabel('Iteration number','Interpreter','none','FontWeight','bold',...
    'FontSize',18,...
    'FontName','Times');

% Create ylabel
ylabel('$\hat{\mathsf{R}}$','Interpreter','latex','FontSize',20,'FontName','Times');

ylim([A B])
xlim([C D])