function Rfigure2(X1, Y1, Y2, transp)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
sz = length(Y1)/6;
A1=min(min(Y1(sz:end),Y2(sz:end)));
B1=max(max(Y1(sz:end),Y2(sz:end)));
%  Auto-generated by MATLAB on 24-Oct-2018 15:46:25
% A1=min(min(Y1))*0.95;
% B1=max(max(Y1))*1.05;
% A2=min(min(Y2))*0.95;
% B2=max(max(Y2))*1.05;
% A = min(A1,A2);
% B = max(B1,B2);
% aux = max(abs(B-1),abs(A-1));
% A = 1-aux;
% B = 1+aux;
A = A1*.9;
B = B1*1.1;
% A = -1;
% B =1;
C = min(X1);
D=max(X1);
% Create figure
figure2 = figure();
if(transp==1)
    fig = gcf;
    fig.Color = 'none';
    fig.InvertHardcopy = 'off';
end
% Create axes
axes1 = axes('Parent',figure2,'LineWidth',2,'YMinorTick','on','XMinorTick','on',...
    'FontSize',16,'FontName','Times','FontWeight','bold',...
    'DataAspectRatio',[((D-C)/(B-A)) 3 1],'Color','none');
box(axes1,'on');
hold(axes1,'all');

% Create plot
for i=1:size(Y1,2)
    plot(X1,Y1(:,i),'LineWidth',3,'Color',[0 0 ((i-1)/size(Y1,2))]);
    plot(X1,Y2(:,i),'LineWidth',3,'LineStyle','--',...
        'Color',[((i-1)/size(Y2,2)) 0 0]);
end

% Create xlabel
xlabel('Iteration number','Interpreter','none','FontWeight','bold',...
    'FontSize',18,...
    'FontName','Times');

% Create ylabel
ylabel('$\det{[\cdot]}$','Interpreter','latex','FontSize',20,'FontName','Times');

ylim([A B])
xlim([C D])