function fig_matrix(Matrix1,xname,yname,str,n)
%CREATEFIGURE(X1, X2, YMatrix1)
%  X1:  vector of x data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Feb-2021 15:15:03

% Create figure
figure1 = figure(n);
X1 = Matrix1(:,1);
Y1 = Matrix1(:,2:end);
ys = size(Y1);
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
% Create multiple lines using matrix input to plot
color = [0.85 0.33 0.10; 0.0 0.45 0.74; 0.93 0.69 0.13; 0 0 0];
color = [color; color];
lin = '-';
sib = 'none';
for i=1:ys(2)
    if(i>=5), lin = '--'; sib = 'o'; end
    name = ['$' str '{' num2str(i,'%d') '}$'];
    plot(X1,Y1(:,i),'LineWidth',2,'Parent',axes1,...
    'DisplayName',name,'LineStyle',lin,'Marker',sib,...
    'Color',[color(i,:)]);
end
% Set the remaining axes properties
A = min(min(X1));
B = max(max(X1));
C = min(min(Y1));
D = max(max(Y1));
if abs(D)<1e-6
    D = 0.001;
else
    if abs(D-C)<1e-6
        C = C - D*0.1;
        D = D + D*0.1;
    end
end
asp = [(B-A)/(D-C) 1 1];
set(axes1,'DataAspectRatio',asp,...
    'FontName','Times','FontSize',12,'XMinorTick','on','YMinorTick','on',...
    'ZMinorTick','on');
xlim([A B]);
ylim([C D]);
% Create ylabel
ylabel({yname},'Interpreter','latex','FontSize',16);

% Create xlabel
xlabel({xname},'FontAngle','italic','Interpreter','latex',...
    'FontSize',16);

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southwest','FontSize',10,'EdgeColor','none',...
    'Color','none','Interpreter','latex');

