function pressure_fig(Matrix1)
%CREATEFIGURE(X1, X2, YMatrix1)
%  X1:  vector of x data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Feb-2021 15:15:03

% Create figure
figure1 = figure(134);
X1 = Matrix1(:,1,:);
Y1 = Matrix1(:,2,:);
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
% Create multiple lines using matrix input to plot
plot(X1(:,:,1),Y1(:,:,1),'LineWidth',2,'Parent',axes1,...
    'DisplayName','$W_{p1}$',...
    'Color',[0.85 0.33 0.10]);
% plot(X1(:,:,2),Y1(:,:,2),'LineWidth',2,'Parent',axes1,...
%     'DisplayName','$W_{p2}$',...
%     'Color',[0.0 0.45 0.74]);
% plot(X1(:,:,3),Y1(:,:,3),'LineWidth',2,'Parent',axes1,...
%     'DisplayName','$W_{p3}$',...
%     'Color',[0.93 0.69 0.13]);
% plot(X1(:,:,4),Y1(:,:,4),'LineWidth',2,'Parent',axes1,...
%     'DisplayName','$W_{p4}$',...
%     'Color',[0 0 0]);
% Set the remaining axes properties
A = min(min(X1));
B = max(max(X1));
C = min(min(Y1));
D = max(max(Y1));
if abs(D)<1e-6
    D = 0.001;
else
    if abs(D-C)<1e-6
        C = C - D*0.1;
        D = D + D*0.1;
    end
end
asp = [(B-A)/(D-C) 1 1];
set(axes1,'DataAspectRatio',asp,...
    'FontName','Times','FontSize',12,'XMinorTick','on','YMinorTick','on',...
    'ZMinorTick','on');
xlim([A B]);
ylim([C D]);
% Create ylabel
ylabel({'Pressure $MPa$'},'Interpreter','latex','FontSize',16);

% Create xlabel
xlabel({'time (days)'},'FontAngle','italic','Interpreter','latex',...
    'FontSize',16);

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeast','FontSize',10,'EdgeColor','none',...
    'Color','none','Interpreter','latex');

