function errorfigure(X1, YMatrix1, v)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Dec-2021 18:17:49

A = min(X1);
B = max(X1);
C = min(min(YMatrix1));
D = max(max(YMatrix1))*1.2;
ratio = (B-A)/(D-C);

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to semilogy
semilogy(X1,YMatrix1,'LineWidth',2);

% Create ylabel
ylabel(['Mean Squared Error ($\mathsf{F}^{obs}_{' v '}$)'],'FontSize',14,'Interpreter','latex');

% Create xlabel
xlabel('Iteration','FontSize',14,'Interpreter','latex');

xlim([A B]);

ylim([C D]);

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[ratio 2 1],'FontName','Times','FontSize',12,...
    'TickDir','both','TickLabelInterpreter','latex','XMinorTick','on',...
    'YMinorTick','on','YScale','log');
