function normhist(data1,lab)
%CREATEFIGURE(data1, function1)
%  DATA1:  histogram data
%  FUNCTION1:  function f(x)

%  Auto-generated by MATLAB on 07-Oct-2021 10:45:56

A = min(data1);
B = max(data1);
x = [A:(B-A)/200:B];
m = mean(data1);
s = std(data1);
y = normpdf(x,m,s);
C = 0.0;
D = max(y) * 1.2;

ratio = (B-A)/(D-C);

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'LineWidth',1,'FaceColor',[0.8 0.8 0.8],...
    'Normalization','pdf', 'BinWidth',0.2,'DisplayName',lab);

% Create fplot
% if lambda < 1
%     n = ['{\frac{1}{' num2str(1/lambda,'%3.1f') '}}'];
% else
%     n = num2str(lambda,'%3.1f');
% end
% name = ['$f(t)={\displaystyle{' n '}}\  {e}^{-{' n '} {t}}$'];
name = 'pdf';
plot(x,y,'Parent',axes1,'MarkerSize',6,...
    'Color',[0 0.447058823529412 0.741176470588235],...
    'LineWidth',3,'DisplayName', name);

% Create ylabel
ylabel('$f(t)$','FontSize',16,'Interpreter','latex');

% Create xlabel
xlabel('$t$','FontSize',16,'Interpreter','latex');

%
ylim(axes1,[C D]);
xlim(axes1,[A B]);

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[ratio 1 1],'FontName','Times','FontSize',14,...
    'TickDir','both','TickLabelInterpreter','latex','XMinorTick','on',...
    'YMinorTick','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','FontSize',11,'EdgeColor','none',...
    'Color','none');

