function [X1 Y1]=fig_cut2D(G, sol, Lx, cwell, Lz, pw, vinj, rw, qwprod, fluid, rock)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
    TOL= 1e-0;
    x  = linspace(rw, Lx, 50);
    X1 = [];
    Y1 = [];
    y  = cwell(2);
    z  = Lz/2.0;
    for i=1:numel(x)
        p = [x(i) y z];
        d = 1e30;
        for j=1:G.cells.num
            aux = norm(G.cells.centroids(j,:) - p);
            if (aux < d)
                d = aux;
                pos = j;
            end
        end
        X1 = [X1; G.cells.centroids(pos,1)];
        Y1 = [Y1; sol.pressure(pos)];
    end
    [X1 indx] = sort(X1);
    Y1 = Y1(indx);
    x = X1;
    p = panaliticaRadial(x,rw,vinj,pw,fluid,rock.perm,Lz);
    xmin = min(x);
    xmax = max(x);
    ymin = min(Y1);
    ymax = max(Y1)*1.0;
    aspc = [1 (ymax-ymin)/(xmax-xmin) 1];
    % Analytic

    %  Auto-generated by MATLAB on 19-Feb-2021 10:51:09
    % Create figure
    figure1 = figure;

    % Create axes
    axes1 = axes('Parent',figure1);
    hold(axes1,'on');

    % Create plot
    plot(x,Y1,'-o','LineWidth',2);

    % Create ylabel
    ylabel({'$p (Pa)$'},'FontSize',16,'Interpreter','latex');

    % Create xlabel
    xlabel({'$x (m)$'},'FontSize',16,'Interpreter','latex');

    box(axes1,'on');
    % Set the remaining axes properties
    set(axes1,'Color','none','DataAspectRatio',aspc,'FontName',...
        'Times','FontSize',14,'LineWidth',1,'TickLabelInterpreter','latex',...
        'TitleFontWeight','normal','XColor',[0 0 0],'XMinorTick','on','YColor',...
        [0 0 0],'YMinorTick','on','ZColor',[0 0 0]);
    % Uncomment the following line to preserve the X-limits of the axes
    xlim(axes1,[xmin xmax]);
    % Uncomment the following line to preserve the Y-limits of the axes
    ylim(axes1,[ymin ymax]);
end
