function newtonfigura2d(F1,F2,limites,x0)
%CREATEFIGURE(Function1)
%  FUNCTION1:  fsurf function

%  Auto-generated by MATLAB on 07-Oct-2020 17:25:51

% Create figure
figure1 = figure(34);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create fsurf
fsurf(F1,limites,'Parent',axes1,'EdgeColor','none',...
    'FaceAlpha',1,'LineWidth',0.1);
fsurf(F2,limites,'Parent',axes1,'EdgeColor',[0 0 0],...
    'FaceAlpha',1,'LineWidth',0.1);
fsurf(F2*0,limites,'Parent',axes1,'EdgeColor','none',...
    'FaceAlpha',0.5,'LineWidth',0.1,'FaceColor',[0,0,0]);
plot3(x0(1),x0(2),double(F2(x0(1),x0(2))),...
    'MarkerFaceColor',[1 1 0],...
    'Color',[1 1 0],...
    'MarkerSize',6,...
    'Marker','o',...
    'LineStyle','none')
plot3(x0(1),x0(2),double(F1(x0(1),x0(2))),...
    'MarkerFaceColor',[1 1 0],...
    'Color',[1 1 0],...
    'MarkerSize',6,...
    'Marker','o',...
    'LineStyle','none')
% Create zlabel
zlabel({'$f(x_1,x_2)$'},'Interpreter','latex','FontSize',20);

% Create ylabel
ylabel({'$x_2$'},'Interpreter','latex','FontSize',20);

% Create xlabel
xlabel({'$x_1$'},'Interpreter','latex','FontSize',20);

view(axes1,[-37.5 35]);
%view(axes1,[0 90]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'AmbientLightColor','none','BoxStyle','full',...
    'Color','none','FontName','Times','FontSize',12,...
    'LineWidth',1,'TickLabelInterpreter','latex');
